name: Post Image to Bluesky

on:
  schedule:
    # Run at 7:00 and 17:00 UTC every day
    - cron: "0 7 * * *"
    - cron: "0 17 * * *"

  workflow_dispatch: # Allow manual triggering from GitHub
    inputs:
      run_reason:
        description: 'Reason for manual run'
        required: false

jobs:
  post_image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Ensure folder permissions
      - name: Set folder permissions
        run: chmod -R 755 images posted

      # Step 5: Run the bot script
      - name: Run Bluesky bot
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python bot.py

      # Step 6: Move posted image to 'posted/' folder
      - name: Debug move image
        run: |
          echo "Current working directory:"
          pwd  # Prints the current working directory
          echo "Files in 'images' directory:"
          ls -l images/  # Lists all files in the 'images' folder
          
          IMAGE_PATH=$(python -c "import os, glob; print(os.path.abspath(next(iter(sorted(glob.glob('images/*.jpg'))))))")
          echo "Image path: $IMAGE_PATH"  # Prints the absolute image path
          
          POSTED_DIR='posted'
          mkdir -p $POSTED_DIR
          
          # Check if image exists before attempting to move it
          if [ -f "$IMAGE_PATH" ]; then
            mv $IMAGE_PATH $POSTED_DIR/
            echo "Moved $IMAGE_PATH to $POSTED_DIR"
          else
            echo "Image not found: $IMAGE_PATH"
          fi

