name: Post Image to Bluesky

on:
  schedule:
    # Run at 7:00 and 17:00 UTC every day
    - cron: "0 7 * * *"
    - cron: "0 17 * * *"

  workflow_dispatch: # Allow manual triggering from GitHub
    inputs:
      run_reason:
        description: 'Reason for manual run'
        required: false

jobs:
  post_image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the bot script
      - name: Run Bluesky bot
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python bot.py

      # Step 5: Debugging and check file status
      - name: Debug file status
        run: |
          echo "Current working directory:"
          pwd  # Prints the current working directory
          echo "Files in 'images' directory:"
          ls -l images/  # Lists all files in the 'images' folder

      # Step 6: Delete posted image
      - name: Delete posted image from 'images' folder
        run: |
          IMAGE_PATH=$(python -c "import os, glob; print(os.path.abspath(next(iter(sorted(glob.glob('images/*.jpg'))))))")
          echo "Image path: $IMAGE_PATH"  # Prints the absolute image path
          
          # Delete the image
          if [ -f "$IMAGE_PATH" ]; then
            rm "$IMAGE_PATH"
            echo "Deleted $IMAGE_PATH"
          else
            echo "Image not found: $IMAGE_PATH"
            exit 1
          fi

      # Step 7: Commit and push the changes to GitHub
      - name: Commit and push the deleted image
        run: |
          # Set the local Git user information for this repository
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage all changes (including deleted files)
          git add -A
          
          # Commit the changes with a message
          git commit -m "Delete posted image"
          
          # Push the commit to GitHub using the GitHub token for authentication
          git push https://github-actions[bot]:${{ secrets.GH_TOKEN }}@github.com/utjecajnik/bskyutj.git HEAD:main || echo "No changes to push"
